security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [ in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        assets:
            pattern:  ^/(_(profiler|wdt)|css|imagens|js|assetic|bundles|components|fonts)/
            security: false
        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path: /
                use_referer: true
            logout:
                path: /logout
                target: /
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/workouts, role: IS_AUTHENTICATED_FULLY }